language: php
php:
    - 7.0
    - 7.1
install:
    - composer install --prefer-source --no-interaction
before_script:
    - phpenv rehash
script:
    - ./bin/test.sh
env:
    global:
        - PHPUNIT_TESTSUITE=linux
